#!/usr/bin/env bash

# Autor: Lissandro
# Descrição: Automatizar atualizações dos pacotes .Deb, Snap e Flatpak
# Version: 3.0
# License: GPL 2

# Atualizar os repositórios

echo [Iniciando Ups...]
sudo apt update

# Atualizar pacotes .deb 
 
echo "                      
[Atualizar pacotes .deb...]"
sudo apt dist-upgrade -y

# Remover pacotes desnecessários

echo "                              
[Remover pacotes desnecessários...]"

sudo apt autoremove --purge -y

# Atualizar pacotes Snap

#echo "                
#[Atualizar Snaps...]"
#sudo snap refresh

# Atualizar pacotes Flatpaks

echo "                  
[Atualizar Flatpaks...]"
sudo flatpak update -y

# Finalizando

echo "                    
Pronto! 
Atualizações finalizadas :)"

